version: "3.8"
services:
  db:
    image: postgres:14.1
    container_name: frameworsk_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: framework
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: framework_db
    networks:
      - app-network

networks:
  app-network:
    external: true
